version: "3.8"
services:
  mongodb:
    image: mongo:4.0.19
    ports:
      - "27005:27017"
    volumes:
      - ./data/mongo:/data/db
  sqldb:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres